import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "@/stack";
import { ThemeProvider } from '@/context/ThemeContext';
import { Toaster } from "@/components/ui/sonner";
import { LoadingProvider } from '@/context/LoadingContext';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <ConvexClientProvider>
              <ThemeProvider>
                <LoadingProvider>
                  {children}
                  <Toaster />
                </LoadingProvider>
              </ThemeProvider>
            </ConvexClientProvider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}